server:
  port: 0

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgresSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
properties:
  hibernate.format_sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/fresh
  username: mfi
  password: postgres
  driver-class-name: org.postgresql.Driver

spring:
  application:
    name: catalog-service
  sql:
    init:
      platform: postgres


logging:
  level:
    com.example.com.example.CatalogService: DEBUG