server:
  port: 0

spring:
  application:
    name: user-service
  sql:
    init:
      platform: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: //gmail주소 입력
    password: //2단계인증으로 나온 비번 입력
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgresSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
properties:
  hibernate.format_sql: true


spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/fresh2
  username: mfi
  password: mfi
  driver-class-name: org.postgresql.Driver

greeting:
  message: Welcome to the Simple E-Commerce.

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    com.example.User_service.client: DEBUG