server:
  port: 0

spring:
  application:
    name: user-service
  sql:
    init:
      platform: postgres


spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgresSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
properties:
  hibernate.format_sql: true


spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/fresh1
  username: mfi
  password: postgres
  driver-class-name: org.postgresql.Driver





greeting:
  message: Welcome to the Simple E-Commerce.

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka








logging:
  level:
    com.example.User_service.client: DEBUG